version: '3.9'
services:
  api:
    build:
      context: ./api
        
    networks:
      - app-network

  web:
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge