version: '3.9'
services:
  web:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - app-network


  db:
    image: mysql:latest
    restart: always
    ports:
      - "5001:3306"
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  api1:
    build:
      context: ./api
    restart: always
    networks:
      - app-network
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=mydatabase
    depends_on:
      - db
  api2:
    build:
      context: ./api
    restart: always
    networks:
      - app-network
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=mydatabase
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  db-data: